image: jakzal/phpqa:php8.1

before_script:
    - cd symfony
    - composer install
    - composer require --dev squizlabs/php_codesniffer

cache:
    paths:
        - vendor/

stages:
    - ReactCheck

eslint:
    stage: ReactCheck
    image: node:18-alpine
    script:
        - npm ci
        - npx eslint --format gitlab .
    artifacts:
        reports:
            codequality: gl-codequality.json

