stages:
  - test

variables:
  SYMFONY_DEPRECATIONS_HELPER: weak

test:
  stage: test
  image: php:7.4
  services:
    - mysql:5.7
  before_script:
    - apt-get update
    - apt-get install -y git zip unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --prefer-dist --no-progress --no-interaction
    - cp .env.dist .env
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
  script:
    - vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
    - vendor/bin/phpstan analyze src/ tests/
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-clover build/logs/clover.xml
  artifacts:
    reports:
      junit: junit.xml
