image: node:18-alpine

before_script:
    - cd biblio
    - npm install
    - npm install --save-dev eslint eslint-formatter-gitlab


stages:
    - ReactCheck

eslint:
    stage: ReactCheck
    script:
        - npm ci
        - npx eslint --format gitlab .
    artifacts:
        reports:
            codequality: gl-codequality.json

