default:
  image: php:7.4-apache

cache:
  paths:
    - vendor/

stages:
  - "analysis"
  - "tests"

static_analysis:
  stage: analysis
  script:
    - sh scripts/ci-php-install.sh
    - php bin/composer.phar require --dev phpstan/phpstan
    - php vendor/bin/phpstan.phar analyse src --level=1

phpunit:
  stage: test
  script:
    - sh scripts/ci-php-install.sh
    - php bin/composer.phar install -o
    - php bin/composer.phar require --dev symfony/phpunit-bridge
    - sh scripts/php_test_run.sh