image: jakzal/phpqa:php8.1

before_script:
  - cd symfony
  - composer install

cache:
  paths:
    - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker --path=./composer.lock
  allow_failure: false


phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
  allow_failure: false
  when: on_success

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false
  when: on_success

twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_failure: false
  when: on_success

#unit-tests:
#  stage: UnitTests
#  script:
#    - php ./vendor/bin/phpunit --configuration ./phpunit.xml
#  allow_failure: false
#  when: on_success

