image: jakzal/phpqa:php8.1

before_script:
    - composer install

cache:
    paths:
        - ./symfony/vendor/

stages:
    - SecurityChecker
    - CodingStandards
    - UnitTests
    - deploy

security-checker:
    stage: SecurityChecker
    script:
        - local-php-security-checker  --path=./symfony/composer.lock
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR12 --ignore=./symfony/src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: CodingStandards
    script:
        - phpstan analyse ./symfony/src
    allow_failure: false

twig-lint:
    stage: CodingStandards
    script:
        - twig-lint lint ./symfony/templates
    allow_failure: false


pages:
  stage: deploy
  image: tthor/test
  before_script:
    - mkdir -p public
  script:
    - emacs README.org -l htmlize.el --batch --eval "(org-babel-do-load-languages 'org-babel-load-languages '( (python . t) ) )" --eval '(setq org-confirm-babel-evaluate nil)' --eval "(setq org-html-htmlize-output-type 'css)" -f org-html-export-to-html --kill
    - cp README.html ./symfony/public/index.html
    - cp *.png ./symfony/public/
  artifacts:
    paths:
      - public
  only:
    - master

