image: jakzal/phpqa:php8.1

before_script:
  - cd symfony
  - composer install

cache:
  paths:
    - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker --path=./composer.lock
  allow_failure: false
  extends: job_template

phpcs:
  stage: CodingStandards
  script:
    - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
  allow_failure: false
  extends: job_template

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false
  extends: job_template

twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_failure: false
  extends: job_template

unit-tests:
  stage: UnitTests
  script:
    - php ./vendor/bin/phpunit --configuration ./phpunit.xml
  allow_failure: false
  extends: job_template

# Bloquer le push ou le merge si le job de SecurityChecker ou de UnitTests échoue
job_template:
    rules:
    - if: '($CI_JOB_NAME == "SecurityChecker" || $CI_JOB_NAME == "UnitTests") && $CI_JOB_STATUS != "success"'
    when: always
    allow_failure: false