<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIx5JGw5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIx5JGw5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIx5JGw5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIx5JGw5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIx5JGw5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ix5JGw5',
    'container.build_id' => '081229bd',
    'container.build_time' => 1680159551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIx5JGw5');
