<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRYVjFXD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRYVjFXD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRYVjFXD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRYVjFXD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRYVjFXD\App_KernelDevDebugContainer([
    'container.build_hash' => 'RYVjFXD',
    'container.build_id' => '452bcd19',
    'container.build_time' => 1680092158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRYVjFXD');
