<?php

namespace ContainerG9gJH3S;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IjNPEfrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IjNPEfr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IjNPEfr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\APIController::books' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController::empruntLecteur' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController::lastEmprunt' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController::lastPosts' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController::login' => ['privates', '.service_locator.kXKtuJ3', 'get_ServiceLocator_KXKtuJ3Service', true],
            'App\\Controller\\APIController::register' => ['privates', '.service_locator.ERCKR8I', 'get_ServiceLocator_ERCKR8IService', true],
            'App\\Controller\\APIController::research' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController::researchAuthor' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pOptczf', 'get_ServiceLocator_POptczfService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\APIController:books' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController:empruntLecteur' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController:lastEmprunt' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController:lastPosts' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController:login' => ['privates', '.service_locator.kXKtuJ3', 'get_ServiceLocator_KXKtuJ3Service', true],
            'App\\Controller\\APIController:register' => ['privates', '.service_locator.ERCKR8I', 'get_ServiceLocator_ERCKR8IService', true],
            'App\\Controller\\APIController:research' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\APIController:researchAuthor' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pOptczf', 'get_ServiceLocator_POptczfService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\APIController::books' => '?',
            'App\\Controller\\APIController::empruntLecteur' => '?',
            'App\\Controller\\APIController::lastEmprunt' => '?',
            'App\\Controller\\APIController::lastPosts' => '?',
            'App\\Controller\\APIController::login' => '?',
            'App\\Controller\\APIController::register' => '?',
            'App\\Controller\\APIController::research' => '?',
            'App\\Controller\\APIController::researchAuthor' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\APIController:books' => '?',
            'App\\Controller\\APIController:empruntLecteur' => '?',
            'App\\Controller\\APIController:lastEmprunt' => '?',
            'App\\Controller\\APIController:lastPosts' => '?',
            'App\\Controller\\APIController:login' => '?',
            'App\\Controller\\APIController:register' => '?',
            'App\\Controller\\APIController:research' => '?',
            'App\\Controller\\APIController:researchAuthor' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
